version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      PGDATA: /var/lib/postgresql/data/pg_data
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
  webstarterkit:
    image: webstarterkit
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DEBUG=true
      - POSTGRES_HOSTNAME=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pg_data:

