version: '3.4'

services:
  webstarterkit:
    image: webstarterkit
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - GIN_MODE=release
    ports:
      - 8080:8080
